DOCSP-36266 Add Gen AI FAQs
mongodb/docs-landing pull request #159
Opened 2024-02-14 20:04 UTC by ianf-mongodb

https://preview-mongodbianfmongodb.gatsbyjs.io/landing/DOCSP-36266/

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cd1a44cbcd269fa5424c60

2024-02-22 15:07 UTC, ianf-mongodb commented on source/tools-and-connectors.txt
> +      :url: https://preview-mongodbianfmongodb.gatsbyjs.io/landing/DOCSP-36266/generative-ai-faq/
> [!NOTE]  
> This will be updated to the url above before merge: https://www.mongodb.com/docs/generative-ai-faq/

2024-02-22 15:07 UTC, ianf-mongodb commented on source/tools-and-connectors.txt
> +      :url: https://preview-mongodbianfmongodb.gatsbyjs.io/landing/DOCSP-36266/generative-ai-faq/
> [!NOTE]  
> This will be updated to the url above before merge: https://www.mongodb.com/docs/generative-ai-faq/


```suggestion
      :url: https://preview-mongodbianfmongodb.gatsbyjs.io/landing/DOCSP-36266/generative-ai-faq/
```

2024-02-22 15:42 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[suggestion] I think we could shorten this for minimalism

```suggestion
What Data Is Sent To The Model?
~~~~~~~~~~~~~~~~~~~~~~~~
```

2024-02-22 15:50 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +MongoDB does not store inputs or outputs from the model.
[question] (for my own limited knowledge of GenAI tools) Can you clarify the difference between inputs/outouts of the GenAI service versus inputs/outputs of the model?

2024-02-22 19:19 UTC, ltran-mdb2 approved these changes
I left a couple small comments but otherwise this LGTM @ianf-mongodb !

2024-02-22 19:19 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +and services, including within Atlas and in its software products.
that makes sense! Since "its software products" is covered earlier in the sentence ("in its products and services"), I would suggest taking out software products for minimalism. 

```suggestion
and services, including within Atlas.
```

2024-02-22 19:19 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +and services, including within Atlas and in its software products.
Or alternatively, 
```suggestion
and services.
```

2024-02-22 19:19 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +software (Relational Migrator and Compass) you may opt out of input
[nit]

```suggestion
software (Relational Migrator and Compass), you may opt out of input 
```

2024-02-22 19:19 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +For example in MongoDB Compass users can
[nit]

```suggestion
For example, in MongoDB Compass users can 
```

2024-02-22 19:19 UTC, ltran-mdb2 commented on source/generative-ai-faq.txt
> +visualizations powered by GenAI. Additionally,
[suggestion] we could probably make this more active as well

```suggestion
In Charts, Atlas users have the capability to construct 
GenAI powered visualizations. Additionally, 
```

2024-02-27 20:14 UTC, ianf-mongodb commented
@themantissa This page has been updated per the doc for legal language updates.

2024-02-28 18:54 UTC, themantissa requested changes
Got the okay for the links to remain, with one edit to clarify one.  And one fixed link - it went to ToS not AUP.  TY!

2024-02-28 18:54 UTC, themantissa commented on source/generative-ai-faq.txt
> +`Acceptable Use Policy <https://www.mongodb.com/legal/terms-of-use>`_ and
Incorrect link:
```suggestion
`Acceptable Use Policy <https://www.mongodb.com/legal/acceptable-use-policy>`_ and 
```

2024-02-28 18:54 UTC, themantissa commented on source/generative-ai-faq.txt
> +For more detail, refer to the Azure OpenAI data management policy.
We can link if we reword it to:
```suggestion
For more detail, refer to [Azure OpenAI's data management practices](https://learn.microsoft.com/en-us/legal/cognitive-services/openai/data-privacy).
```

2024-02-28 18:54 UTC, themantissa commented on source/generative-ai-faq.txt
> +Monitoring so that no prompts or responses are stored with Azure OpenAI.
```suggestion
for any model training. MongoDB has opted out of [asynchronous Abuse 
Monitoring](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/abuse-monitoring) so that no prompts or responses are stored with Azure OpenAI. 
```

2024-02-28 18:54 UTC, themantissa commented on source/generative-ai-faq.txt
> +MongoDB's current GenAI features are powered by Azure OpenAI. When you
```suggestion
MongoDB's current GenAI features are powered by [Azure OpenAI](https://azure.microsoft.com/en-us/products/ai-services/openai-service). When you 
```

2024-02-28 19:42 UTC, ianf-mongodb reviewed
Updated @themantissa!

2024-02-28 19:44 UTC, themantissa approved these changes
Looks great!  Thank you!

2024-03-05 21:29 UTC, merged